###

GET http://localhost:8080/admin/user HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8080/admin/register HTTP/1.1
Content-Type: application/json

    {
    "email": "Sodoo333333@gmail.com",
    "password" : "1234"
    }

###

POST http://localhost:8080/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###
